version: '3'
services:
  starlette:
    container_name: capy_backend
    build:
      dockerfile: ./Dockerfile
      context: ./backbara
    restart: unless-stopped
    ports:
      - "7777:80"
    environment:
      MONGO_IP: "capy_mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "capybara"

      # Nano ID length https://zelark.github.io/nano-id-cc/
      NANO_ID_LEN: 21

      JWT_EXPIRES_DAYS: 20

      ROOT_ADMIN_NAME: "capy"

      SMTP_DOMAIN: ""
      SMTP_MAIN: "no-reply"
      SMTP_HOST: "localhost"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""

      REDIS_HOST: "capy_redis"
      REDIS_PORT: 6379

      # Proxied Frontend URL.
      URL_PROXIED: "http://localhost:7778"
    volumes:
      # If you change 'SAVE_PATH' this needs to be changed,
      # changing 'SAVE_PATH' is not recommended.
      - capydata:/app/capybaras
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    container_name: capy_frontend
    build:
      dockerfile: ./Dockerfile
      context: ./frontbara
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_URL_PROXIED: "http://localhost:7777"
    restart: unless-stopped
    ports:
      - "7778:80"

  redis:
    container_name: capy_redis
    image: redis
    volumes: 
      - redis:/data
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: capy_mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  mongodbdata:
    driver: local
  capydata:
    driver: local
