from enum import Enum
from typing import Optional

from pydantic import BaseConfig, BaseModel, Field
from starlite import UploadFile

WEAPONS = [
    "Watermelon catapult",
    "Chair-jitsu",
    "Tickle machine",
    "Ticklish attack",
    "Marshmallow launcher",
    "Giggle bomb",
    "Confetti blaster",
    "Feather of doom",
    "Banana peel of chaos",
    "Rainbow ray gun",
    "Bubble wrap armor",
    "Pillow barricade",
    "Rubber chicken nunchucks",
    "Dance-off distraction",
    "Silly string surprise",
    "Hug-powered force field",
    "Laser-guided whoopee cushion",
    "Inflatable sumo wrestler suit",
    "Jellybean catapult",
    "Tickle tornado",
    "Marshmallow ninja stars",
    "Papercut paper airplanes",
    "Silly walk attack",
    "Uncontrollable laughter gas",
    "Gummy bear grenade",
    "Disarming dad jokes",
    "Confetti cannon chaos",
    "Feather boa whip",
    "Banana peel slide trap",
    "Rubber chicken boomerang",
    "Dancing distraction",
    "Bubblegum bubble blast",
    "Giant hug bear trap",
    "Giggling potion",
    "Whoopee cushion landmines",
    "Rainbow parachute pants",
    "Pillow fight frenzy",
    "Squishy stress ball bazooka",
    "Tofu ninja stars",
    "Jellyfish tickle attack",
    "Paperclip slingshot",
    "Laughing gas balloons",
    "Gummy worm whip",
    "Silly string spider web",
    "Laser pointer pranks",
    "Marshmallow blizzard",
    "Confetti tornado",
    "Banana boomerang",
    "Rubber ducky army",
    "Dance battle distraction",
    "Bubblegum bubble bomb",
    "Giant teddy bear hug",
    "Giggling contagious disease",
    "Whoopee cushion minesweeper",
    "Rainbow unicorn launcher",
    "Pillow fortress",
    "Squirt gun showdown",
    "Tofu foam finger",
    "Jellybean slingshot",
    "Peanut butter jelly dance",
    "Laughing yoga",
    "Gummy bear storm",
    "Silly string lasso",
    "Laser tag tickle edition",
    "Marshmallow catapult",
    "Confetti shower surprise",
    "Banana slip-n-slide",
    "Rubber duck squad",
    "Disco dance diversion",
    "Bubble gum bubblegasm",
    "Giant inflatable hug",
    "Giggling fit frenzy",
    "Whoopee cushion stealth mode",
    "Rainbow paintball party",
    "Pillow fight championship",
    "Squishy stress ball slingshot",
    "Tofu boomerang",
    "Jellybean shower",
    "Peanut butter jelly time flash mob",
    "Laughing gas attack",
    "Gummy bear bazooka",
    "Silly string ambush",
    "Laser show tickle extravaganza",
    "Marshmallow madness",
    "Confetti chaos",
    "Banana slip-up",
    "Rubber duck bomb squad",
    "Breakdancing distraction",
    "Bubblegum bubble bonanza",
    "Giant hug stampede",
    "Giggling energy beam",
    "Whoopee cushion surprise attack",
    "Rainbow cannon",
    "Pillow battle royale",
    "Squishy stress ball assault",
]

CLASSES = [
    "Chill dude",
    "Barbarian",
    "Bard",
    "Cleric",
    "Fighter",
    "Druid",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
    "Jester",
    "Ninja Accountant",
    "Mage of Mischief",
    "Silly Shaman",
    "Enchanter of Laughter",
    "Bardbarian",
    "Tickle-Me-Mage",
    "Merry Marauder",
    "Comedic Conjurer",
    "Swashbuckling Stand-Up",
    "Warlock of Whimsy",
    "Zen Trickster",
    "Giggling Gladiator",
    "Silly Summoner",
    "Prankster Paladin",
    "Rogue Jokester",
    "Circus Sorcerer",
    "Wizard of Wisecracks",
    "Hilarious Healer",
    "Karaoke King/Queen",
    "Mirthful Marksman",
    "Laughing Luchador",
    "Pun-dit",
    "Jolly Juggler",
    "Chuckling Chef",
    "Amusing Alchemist",
    "Sneaky Sideshow Performer",
    "Bumbling Brawler",
    "Crazy Cartographer",
    "Whimsical Weaponmaster",
    "Mischievous Minstrel",
    "Witty Weatherman",
    "Cheerful Chronomancer",
    "Drunken Dancer",
    "Peculiar Puppeteer",
    "Playful Pyromancer",
    "Gleeful Gadgeteer",
    "Sarcastic Swordmaster",
    "Smiling Scout",
    "Wacky Wordsmith",
    "Hysterical Herbalist",
    "Cackling Captain",
    "Zany Zookeeper",
    "Hapless Hypnotist",
    "Foolish Fire-eater",
    "Meme Magician",
    "Cheesy Charmer",
    "Punny Poet",
    "Bouncy Blacksmith",
    "Madcap Mime",
    "Silly Summoner",
    "Ditzy Duelist",
    "Quirky Quack Doctor",
    "Giddy Gambler",
    "Crazy Cryptographer",
    "Amiable Archer",
    "Eccentric Enchanter",
    "Screaming Swordsman",
    "Foolish Fanatic",
    "Clueless Conjurer",
    "Giggling Geomancer",
    "Sarcastic Scout",
    "Wacky Weather Witch",
    "Comical Cultist",
    "Joking Jester",
    "Bumbling Bluffer",
    "Mad Scientist",
    "Cheerful Caveman/Cavewoman",
    "Puny Paladin",
    "Silly Swashbuckler",
    "Foolish Fortune Teller",
    "Whimsical Warrior",
    "Hilarious Hunter",
    "Cackling Crusader",
    "Laughing Linguist",
    "Dancing Dervish",
    "Playful Plague Doctor",
    "Gleeful Gladiator",
    "Sarcastic Sorcerer",
    "Wacky Warlock",
    "Mirthful Monk",
    "Clumsy Cleric",
    "Amusing Adventurer",
    "Jovial Journalist",
    "Bumbling Bard",
    "Mad Mercenary",
    "Cheeky Chef",
    "Punny Pirate",
]


class RelationshipEnum(Enum):
    taken = "taken"
    single = "single"
    not_looking = "not looking"


class SubmitModal(BaseModel):
    image: UploadFile
    name: Optional[str] = Field(None, max_length=24, regex="^[a-zA-Z_ ]*$")
    relationship_status: RelationshipEnum = RelationshipEnum.single

    class Config(BaseConfig):
        arbitrary_types_allowed = True
