name: Python workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Lint with flake8
        run: |
          pip install black
          black app/ --check
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install pyright
        run: npm install pyright -g
      - name: Run pyright
        run: pyright ./*
